modLoader="javafml"
loaderVersion="${loader_version_range}"
logoFile="logo.png"
license="MIT"
issueTrackerURL="https://github.com/NilsGameKing/thermies-tinkering/issues"

[[mods]]
modId="thermies_tinkering"
version="0.0.97"
displayName="Thermie's Tinkering"
displayURL="A moment, please."

authors="NilsGameKing"
description='''
  A Tinkers' Construct 3 Addon, focusing on "well" "balanced" tool materials.
  '''

[[dependencies.thermies_tinkering]]
modId="forge"
mandatory=true
versionRange="47.4.0"
ordering="NONE"
side="BOTH"

[[dependencies.thermies_tinkering]]
modId="minecraft"
mandatory=true
versionRange="1.20.1"
ordering="NONE"
side="BOTH"

[[dependencies.thermies_tinkering]]
modId="tconstruct"
mandatory=true
versionRange="3.9.1.19"
ordering="NONE"
side="BOTH"